export const CHAT_TYPE_MESSAGE = "CHAT_TYPE_MESSAGE";
export const CHAT_TYPE_UPDATE = "CHAT_TYPE_UPDATE";
export const CHAT_TYPE_DELETE = "CHAT_TYPE_DELETE";
export const USER_TYPE_CONNECT = "USER_TYPE_CONNECT";
export const USER_TYPE_DISCONNECT = "USER_TYPE_DISCONNECT";
